Disable default features for `bitcoin`
Kixunil/bip21 pull request #15
Opened 2023-04-17 19:31 UTC by benthecarman

This makes it so this crate is more usable in a `no-std` context and does not automatically bring along a std version of `bitcoin`

2023-04-18 08:49 UTC, Kixunil requested changes
Oh, how could I forget? Thanks for bringing this up!

2023-04-18 08:49 UTC, Kixunil commented on Cargo.toml
>  std = ["percent-encoding-rfc3986/std"]
This should depend on `bitcoin/std`

2023-04-18 08:49 UTC, Kixunil commented on Cargo.toml
> +default = ["bitcoin/default"]
I don't think this is needed once we have `std` dependency.

2023-04-19 06:43 UTC, benthecarman commented
Fixed!

2023-04-19 06:54 UTC, Kixunil approved these changes
Thanks!

2023-04-19 06:54 UTC, merged